#!/bin/sh 

SCRIPT_NAME=$0
PARAM1=$1

# need full path because of cd later in script logic
HASHFILE=scripts/software_dir_sha256.txt
FULL_SCRIPT_NAME=`realpath $0`
FULLHASHFILE=`dirname $FULL_SCRIPT_NAME`/$HASHFILE
SOFTWARE_DIR=/local/software

usage ()
{
  echo
  echo "Usage: `basename $SCRIPT_NAME` { check | calc}"

  return 0
}

check_hashes ()
{
  if [ ! -r "$HASHFILE" ] ; then
    echo "No checksum file found!"
    return 1
  fi

  cd $SOFTWARE_DIR
  sha256sum -c $HASHFILE
  
  return 0
}

calc_hashes ()
{
  if [ -e "$FULLHASHFILE" ] ; then
    rm -f "$FULLHASHFILE"
  fi

  cd $SOFTWARE_DIR
  sha256sum -b *.tar >> $FULLHASHFILE 2>/dev/null
  cd domino10
  sha256sum -b *.tar >> $FULLHASHFILE 2>/dev/null
  sha256sum -b *.taz >> $FULLHASHFILE 2>/dev/null

  if [ -e "$FULLHASHFILE" ]; then
    echo "Calc hash for `cat $FULLHASHFILE |wc -l` file(s) [`date -d@$SECONDS -u +%T`]"
  else
    echo "No Files found to calculate hash"
  fi

  return 0
}

echo

case "$PARAM1" in
	
  check)
    check_hashes 
    ;;

  calc)
    calc_hashes
    ;;

  help|-?)
    usage
    ;;

  *)

    if [ -z "$PARAM1" ]; then
      usage 
    else
      echo "Invalid command:" [$PARAM1]
      usage 
    fi
    ;;

esac

echo 
exit 0
