
############################################################################
# Copyright Nash!Com, Daniel Nashed 2019, 2021 - APACHE 2.0 see LICENSE
# Copyright IBM Corporation 2015, 2019 - APACHE 2.0 see LICENSE
############################################################################

FROM redhat/ubi8

# External arguments with a default value
ARG BASE_IMAGE=
ARG LinuxYumUpdate=
ARG DownloadFrom=
ARG PROD_NAME=
ARG PROD_VER=
ARG PROD_FP=
ARG PROD_HF=
ARG DominoResponseFile=
ARG DominoMoveInstallData=
ARG LocalInstallDir=/tmp/install
ARG DominoUserID=
ARG DOMINO_LANG=
ARG DOCKER_TZ=
ARG GIT_INSTALL=
ARG OPENSSL_INSTALL=
ARG SPECIAL_CURL_ARGS=
ARG SPECIAL_WGET_ARGUMENTS=
ARG VERSE_VERSION=

USER root

# Copy Install Files to container
COPY install_dir $LocalInstallDir

# Prepare environment for Domino
# Update, Install required packages and run separate install script

RUN yum install -y openssl perl bc which nano unzip lsof gdb file net-tools hostname cpio procps-ng diffutils glibc-langpack-en && \
  $LocalInstallDir/install_domino.sh && \
  rm -rf $LocalInstallDir

HEALTHCHECK --interval=60s --timeout=10s CMD /domino_docker_healthcheck.sh

# Expose Ports NRPC SMTP HTTP POP3 IMAP LDAP HTTPS LDAPS IMAPS POP3S DIIOP DIIOPS
EXPOSE 1352 25 80 110 143 389 443 636 993 995 63148 63149

ENTRYPOINT ["/domino_docker_entrypoint.sh"]

USER 1000

