
############################################################################
# Copyright Nash!Com, Daniel Nashed 2019, 2020 - APACHE 2.0 see LICENSE
# Copyright IBM Corporation 2015, 2019 - APACHE 2.0 see LICENSE
############################################################################

FROM orel:latest

# Headers
LABEL DominoDocker.maintainer="thomas.hampel, daniel.nashed@nashcom.de"

# External arguments with a default value
ARG BASE_IMAGE=
ARG LinuxYumUpdate=
ARG DownloadFrom=
ARG PROD_NAME=
ARG PROD_VER=
ARG PROD_FP=
ARG PROD_HF=
ARG DominoResponseFile=
ARG DominoMoveInstallData=
ARG LocalInstallDir=/tmp/install
ARG DominoUserID=
ARG DOMINO_LANG=
ARG DOCKER_TZ=
ARG GIT_INSTALL=
ARG OPENSSL_INSTALL=
ARG SPECIAL_CURL_ARGS=
ARG SPECIAL_WGET_ARGUMENTS=

USER root

# Copy Install Files to container
COPY install_dir $LocalInstallDir
COPY dummy /license/accepted

# Prepare environment for Domino
# Update, Install required packages and run separate install script

# Set distribution to CentOS until Astra Linux is supported
# Confirm License and copy back the bash to original location


RUN echo "CentOS Linux release 7.6.1810 (Core)" > /etc/centos-release && \
  cp -f /bin/bash.orig /bin/bash && \
  apt-get update && \
  apt-get install -y apt-utils && \
  apt-get  install -y bc unzip rsync lsof gdb cpio && \
  $LocalInstallDir/install_domino.sh && \
  rm -rf $LocalInstallDir

HEALTHCHECK --interval=60s --timeout=10s CMD /domino_docker_healthcheck.sh

# Expose Ports NRPC HTTP POP3 IMAP LDAP HTTPS LDAPS IMAPS POP3S DIIOP DIIOPS
EXPOSE 1352 80 110 143 389 443 636 993 995 63148 63149

ENTRYPOINT ["/domino_docker_entrypoint.sh"]

USER notes

