kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1

metadata:
  name: domino-admin-role-binding
  namespace: default

subjects:
- kind: ServiceAccount
  name: domino-admin
  namespace: default

roleRef:
  kind: Role
  name: domino-admin-role
  apiGroup: rbac.authorization.k8s.io
