kind: Role
apiVersion: rbac.authorization.k8s.io/v1

metadata:
  name: domino-admin-role
  namespace: default 

rules:

- apiGroups: [""]
  resources: ["pods", "persistentvolumeclaims" ]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
