version: '3.6'
services:

  safelinx:

    image: ${CONTAINER_IMAGE}
    container_name: ${CONTAINER_NAME}
    hostname: ${CONTAINER_HOSTNAME} 
    stop_grace_period: 60s

    environment:
      DOMINO_ORG: ${DOMINO_ORG}
      LDAP_HOST: ${LDAP_HOST}
      CERTMGR_HOST: pluto.csi-domino.com
      CERTMGR_CHECK_INTERVAL: 5

    cap_add:
      - SYS_PTRACE

    ports:
      - ${CONTAINER_HTTPS_PORT}:443

    volumes:
      - safelinx_vol:/opt/hcl/SafeLinx/datastore

      - ./cert-mount:/cert-mount

volumes:

  safelinx_vol:
    name: ${CONTAINER_VOLUME}
    external: false

