version: '3.6'
services:

  safelinx:

    image:          ${CONTAINER_IMAGE}
    container_name: ${CONTAINER_NAME}
    hostname:       ${CONTAINER_HOSTNAME}
    stop_grace_period: 60s
    network_mode: "host"
    privileged: true

    environment:
      DOMINO_ORG:     ${DOMINO_ORG}
      LDAP_HOST:      ${LDAP_HOST}
      LDAP_PORT:      ${LDAP_PORT}
      LDAP_SSL:       ${LDAP_SSL}
      LDAP_USER:      ${LDAP_USER}
      LDAP_PASSWORD:  ${LDAP_PASSWORD}

      ENABLE_NOMAD:   ${ENABLE_NOMAD}
      ENABLE_VERSEHA: ${ENABLE_VERSEHA}
      ENABLE_VPN:     ${ENABLE_VPN}

      VERSE_DOMINO_HOST:  ${VERSE_DOMINO_HOST}

      VPN_HOST_ADDRESS:           ${VPN_HOST_ADDRESS}
      VPN_SUBNET_MASK:            ${VPN_SUBNET_MASK}
      VPN_ENABLE_ROUTING:         ${VPN_ENABLE_ROUTING}
      VPN_ROUTE:                  ${VPN_ROUTE}
      VPN_TARGET_ADAPTER:         ${VPN_TARGET_ADAPTER}
      VPN_MULTI_SIGNON:           ${VPN_MULTI_SIGNON}
      VPN_ENABLE_DNS:             ${VPN_ENABLE_DNS}
      VPN_PRIMARY_DNS_SERVER:     ${VPN_PRIMARY_DNS_SERVER}
      VPN_SECONDARY_DNS_SERVER:   ${VPN_SECONDARY_DNS_SERVER}

      CERTMGR_HOST:           ${CERTMGR_HOST}
      CERTMGR_CHECK_INTERVAL: ${CERTMGR_CHECK_INTERVAL}

    cap_add:
      - SYS_PTRACE

    networks:
      safelinx_net:
        ipv4_address: 172.30.0.2

    ports:
      - ${CONTAINER_HTTPS_PORT}:443

    volumes:
      - safelinx_vol:/opt/hcl/SafeLinx/datastore
      - ./cert-mount:/cert-mount
    
    devices:
      - /dev/net/tun

volumes:

  safelinx_vol:
    name: ${CONTAINER_VOLUME}
    external: false


networks:

  safelinx_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24

