############################################################################
# Copyright Nash!Com, Daniel Nashed 2019, 2022 - APACHE 2.0 see LICENSE
# Copyright IBM Corporation 2015, 2019 - APACHE 2.0 see LICENSE
############################################################################

FROM redhat/ubi8 

# External arguments with a default value
ARG LinuxYumUpdate=
ARG DownloadFrom=
ARG PROD_NAME=
ARG PROD_VER=
ARG PROD_FP=
ARG PROD_HF=
ARG DominoResponseFile=
ARG LocalInstallDir=/tmp/install
ARG DominoUserID=
ARG DOMINO_LANG=
ARG DOCKER_TZ=
ARG SPECIAL_CURL_ARGS=
ARG VERSE_VERSION=
ARG CAPI_VERSION=
ARG STARTSCRIPT_VER=
ARG K8S_RUNAS_USER_SUPPORT=
ARG CONTAINER_INSTALLER=hcl

USER root

# Copy install files to container
COPY install_dir_common $LocalInstallDir
COPY install_dir_domino $LocalInstallDir

# Run install script and cleanup. Linux packages installed in separate layer first. 
RUN $LocalInstallDir/install_linux.sh

# Install Domino in a layer separate from Linux packages and updates
RUN $LocalInstallDir/install_domino.sh && \
  rm -rf $LocalInstallDir

HEALTHCHECK --interval=60s --timeout=10s CMD /healthcheck.sh

# Expose Ports NRPC SMTP HTTP POP3 IMAP LDAP HTTPS LDAPS IMAPS POP3S DIIOP DIIOPS
EXPOSE 1352 25 80 110 143 389 443 636 993 995 63148 63149

ENTRYPOINT ["/entrypoint.sh"]

USER 1000
