############################################################################
# Copyright Nash!Com, Daniel Nashed 2023 - APACHE 2.0 see LICENSE
############################################################################

ARG SQUID_BASE_IMAGE=registry.access.redhat.com/ubi9/ubi-minimal
FROM $SQUID_BASE_IMAGE

# External arguments with a default value
ARG LinuxYumUpdate=
ARG LocalInstallDir=/tmp/install

USER root

# Copy Install Files to container
COPY install_dir_common $LocalInstallDir 
COPY install_dir_squid $LocalInstallDir 

# Prepare environment
# Update, Install required packages and run separate install script

RUN $LocalInstallDir/install.sh && \
  rm -rf $LocalInstallDir

# Expose Ports HTTP HTTPS
EXPOSE 3128

ENTRYPOINT ["/entrypoint.sh"]

USER 1000
