############################################################################
# Copyright Nash!Com, Daniel Nashed 2019, 2025 - APACHE 2.0 see LICENSE
# Copyright IBM Corporation 2015, 2019 - APACHE 2.0 see LICENSE
############################################################################

# Build a base image for Linux with all required packages
FROM registry.access.redhat.com/ubi9/ubi:9.5 AS linux_image

# External arguments with a default value
ARG LinuxYumUpdate=
ARG DownloadFrom=
ARG SOFTWARE_REPO_IP=
ARG PROD_NAME=
ARG PROD_VER=
ARG PROD_FP=
ARG PROD_HF=
ARG PROD_DOWNLOAD_FILE=
ARG PROD_FP_DOWNLOAD_FILE=
ARG PROD_HF_DOWNLOAD_FILE=
ARG DominoResponseFile=domino14_full_install.properties
ARG LocalInstallDir=/tmp/install
ARG DominoUserID=
ARG DOMINO_LANG=
ARG DOCKER_TZ=
ARG SPECIAL_CURL_ARGS=
ARG BUILD_SCRIPT_OPTIONS=
ARG VERSE_VERSION=
ARG CAPI_VERSION=
ARG STARTSCRIPT_VER=
ARG K8S_RUNAS_USER_SUPPORT=
ARG CONTAINER_INSTALLER=hcl

USER root

# Copy install files to container
COPY install_dir_common $LocalInstallDir
COPY install_dir_domino $LocalInstallDir

# Run install script and cleanup. Linux packages installed in separate layer first. 
RUN $LocalInstallDir/install_linux.sh

# Create final Domino image from prepared Linux image
FROM linux_image AS domino_image

# Install Domino in a layer separate from Linux packages and updates
RUN $LocalInstallDir/install_domino.sh && \
  rm -rf $LocalInstallDir

HEALTHCHECK --interval=60s --timeout=10s CMD /healthcheck.sh

# Expose Ports NRPC SMTP HTTP POP3 IMAP LDAP HTTPS LDAPS IMAPS POP3S DOMINO-REMOTE-SETUP DIIOP DIIOPS
EXPOSE 1352 25 80 110 143 389 443 636 993 995 2050 8585 63148 63149

ENTRYPOINT ["/entrypoint.sh"]

USER 1000

