  
############################################################################
# Copyright Nash!Com, Daniel Nashed 2019, 2022 - APACHE 2.0 see LICENSE
############################################################################

ARG BASE_IMAGE=
FROM $BASE_IMAGE

# External arguments with a default value
ARG LinuxYumUpdate=
ARG DownloadFrom=
ARG PROD_NAME=
ARG PROD_VER=
ARG PROD_FP=
ARG PROD_HF=
ARG DominoResponseFile=
ARG DominoMoveInstallData=
ARG LocalInstallDir=/tmp/install
ARG DominoUserID=
ARG DOMINO_LANG=
ARG DOCKER_TZ=
ARG GIT_INSTALL=
ARG OPENSSL_INSTALL=
ARG SPECIAL_CURL_ARGS=
ARG VERSE_VERSION=

USER root
WORKDIR /

# Copy Install Files to container
COPY install_dir_common $LocalInstallDir
COPY install_dir_domino $LocalInstallDir

# Prepare environment for Domino
# Update, Install required packages and run separate install script

RUN  $LocalInstallDir/install_domino.sh && \
  yum install -y glibc-langpack-en hostname && \
  rm -rf $LocalInstallDir

HEALTHCHECK --interval=60s --timeout=10s CMD /domino_docker_healthcheck.sh

# Expose Ports NRPC SMTP HTTP POP3 IMAP LDAP HTTPS LDAPS IMAPS POP3S DIIOP DIIOPS
EXPOSE 1352 25 80 110 143 389 443 636 993 995 63148 63149

ENTRYPOINT ["/domino_docker_entrypoint.sh"]

USER 1000

