############################################################################
# Copyright Nash!Com, Daniel Nashed 2022 - APACHE 2.0 see LICENSE
############################################################################

ARG BASE_IMAGE=registry.access.redhat.com/ubi9/ubi-minimal:latest
FROM $BASE_IMAGE

# External arguments with a default value
ARG LinuxYumUpdate=
ARG DownloadFrom=
ARG PROD_NAME=
ARG PROD_VER=
ARG PROD_DOWNLOAD_FILE=
ARG NOMADWEB_VERSION=
ARG MYSQL_INSTALL=
ARG MSSQL_INSTALL=
ARG LocalInstallDir=/tmp/install
ARG SPECIAL_CURL_ARGS=

USER root

# Copy Install Files to container
COPY install_dir_common $LocalInstallDir 
COPY install_dir_safelinx $LocalInstallDir

# Prepare environment for Domino
# Update, Install required packages and run separate install script

RUN $LocalInstallDir/install_linux.sh && \
  $LocalInstallDir/install.sh && \
  rm -rf $LocalInstallDir

HEALTHCHECK --interval=60s --timeout=10s CMD /healthcheck.sh

# Expose Ports HTTP HTTPS SafeLinx Admin/AdminSSL/Monitoring?
EXPOSE 80 443 9555 9559 9557 8889

ENTRYPOINT ["/entrypoint.sh"]

