
############################################################################
# Copyright Nash!Com, Daniel Nashed 2019, 2020 - APACHE 2.0 see LICENSE
# Copyright IBM Corporation 2015, 2019 - APACHE 2.0 see LICENSE
############################################################################

#FROM node:latest
FROM nodered/node-red-docker:latest

# Headers
LABEL DominoDocker.maintainer="thomas.hampel, daniel.nashed@nashcom.de"

# External arguments with a default value
ARG LinuxYumUpdate=
ARG DownloadFrom=
ARG PROD_NAME=
ARG PROD_VER=
ARG PROD_FP=
ARG PROD_HF=
ARG LocalInstallDir=/tmp/install

USER root

# Copy Install Files to container
COPY install_dir $LocalInstallDir

# Prepare environment for Domino
# Update, Install required packages and run separate install script

RUN $LocalInstallDir/install_iam.sh 
  yum clean all >/dev/null && \
  rm -fr /var/cache/yum 


HEALTHCHECK --interval=60s --timeout=10s CMD /iam_healthcheck.sh

# Expose Ports HTTP HTTPS IAM-ADMIN
EXPOSE 80 443 8443

#ENTRYPOINT ["/iam_entrypoint.sh"]

