#!/bin/bash
# Domino Borg Backup script installation

SCRIPT_NAME=$0
PARAM1=$1
SCRIPT_DIR=$(dirname $SCRIPT_NAME)

LOTUS=/opt/hcl/domino
BORG_SCRIPT_DIR=$SCRIPT_DIR/extra/backup/borg
BORG_DOMINO_DIR=$LOTUS/backup/borg

mkdir -p $BORG_DOMINO_DIR
cp $BORG_SCRIPT_DIR/*.sh $BORG_DOMINO_DIR
chmod 755 $BORG_DOMINO_DIR/*.sh

cp $BORG_SCRIPT_DIR/*.dxl $BORG_DOMINO_DIR
chmod 644 $BORG_DOMINO_DIR/*.dxl

exit 0
