
ARG BASE_IMAGE
FROM $BASE_IMAGE

ARG DownloadFrom=
ARG LINUX_UPDATE=
ARG SPECIAL_CURL_ARGUMENTS=

USER root

COPY install_dir /tmp/install_dir

HEALTHCHECK --interval=60s --timeout=10s CMD /domino_docker_healthcheck.sh

RUN /tmp/install_dir/install.sh && \
  rm -rf /tmp/install_dir

# Expose Ports NRPC HTTP POP3 IMAP LDAP HTTPS LDAPS IMAPS POP3S DIIOP DIIOPS

EXPOSE 1352 80 110 143 389 443 636 993 995 63148 63149 

# ENTRYPOINT ["/domino_docker_entrypoint.sh"]

USER notes

