version: '3.6'
services:

  domino:

    image: hclcom/domino:latest 
    container_name: domino-acme-01
    hostname: domino-acme-v12.acme.com
    stop_grace_period: 60s

    environment:
      SetupAutoConfigure: 1
      SERVERSETUP_SERVER_TYPE: first
      SERVERSETUP_ADMIN_FIRSTNAME: John
      SERVERSETUP_ADMIN_LASTNAME: Doe
      SERVERSETUP_ADMIN_PASSWORD: domino4ever
      SERVERSETUP_ADMIN_IDFILEPATH: admin.id
      SERVERSETUP_ORG_CERTIFIERPASSWORD: domino4ever
      SERVERSETUP_SERVER_DOMAINNAME: DominoDemo
      SERVERSETUP_ORG_ORGNAME: Domino-Demo
      SERVERSETUP_SERVER_NAME: domino-demo-v12
      SERVERSETUP_NETWORK_HOSTNAME: domino-acme-v12.acme.com
      LANG: en_US.UTF-8

    cap_add:
      - SYS_PTRACE

    ports:
      - 1353:1352
      - 80:80
      - 443:443

    volumes:
      - domino_vol:/local/notesdata

volumes:

  domino_vol:
    name: domino_acme_01_notesdata
    external: false

