version: '3.6'
services:

  domino:

    image: hclcom/domino:latest 
    container_name: domino-acme-01
    hostname: domino-acme-01.acme.com
    stop_grace_period: 60s

    environment:
      AdminFirstName: John
      AdminLastName: Doe
      AdminPassword: domino4ever
      OrganizationPassword: domino4ever
      DominoDomainName: Acme
      OrganizationName: Acme
      ServerName: domino-acme-01
      LANG: en_US.UTF-8

    cap_add:
      - SYS_PTRACE

    ports:
      - 1353:1352
      - 80:80
      - 443:443

    volumes:
      - domino_vol:/local

volumes:

  domino_vol:
    name: domino_acme_01_local
    external: false

