version: '3.6'
services:

  domino-volt:

    image: hclcom/volt:latest 
    container_name: volt
    hostname: volt.acme.com
    stop_grace_period: 60s

    environment:
      AdminFirstName: John
      AdminLastName: Doe
      AdminPassword: domino4ever
      OrganizationPassword: domino4ever
      DominoDomainName: Acme
      OrganizationName: Acme
      ServerName: volt-acme-01
      ConfigFile: config.json
      LANG: en_US.UTF-8

    cap_add:
      - SYS_PTRACE

    ports:
      - 1353:1352
      - 80:80
      - 443:443

    volumes:
      - volt_vol:/local

volumes:

  volt_vol:
    name: domino_volt
    external: false

