#!/bin/sh 

SCRIPT_NAME=$0
PARAM=$1
PARAM1=$1
PARAM2=$2
PARAM3=$3

DOCKER_CONTAINER=domino10
DOCKER_IMAGE=ibmcom/domino:10.0.0
DOMINO_SHUTDOWN_TIMEOUT=60

usage ()
{
  echo 
  echo
  echo "Usage: `basename $SCRIPT_NAME` { run | start | stop | bash}"
  echo

  return 0
}

case "$PARAM1" in
	
	run)
    docker run -it -p 1352:1352 -p 80:80 -p 443:443 --name $DOCKER_CONTAINER -v notesdata:/local/notesdata $DOCKER_IMAGE
	  exit 0
	  ;;
	  
  start)
    docker start $DOCKER_CONTAINER
	  exit 0
	  ;;

  stop)
    docker stop --time=$DOMINO_SHUTDOWN_TIMEOUT $DOCKER_CONTAINER
	  exit 0
	  ;;

  bash)
    docker exec -it $DOCKER_CONTAINER /bin/bash 
	  exit 0
	  ;;

   REMOVEALL)
     # remove all containers
     docker rm $(docker ps -a -q)
     # remove all images
     docker rmi $(docker images -q)
	  exit 0
	  ;;

  *)

    if [ -z "$PARAM1" ]; then
      usage 
      exit 1
    else
      echo 
      echo "Invalid command:" [$PARAM1]
      usage 
      exit 1
    fi
    echo 
    exit 0
    ;;

esac

rc_exit
