#!/bin/bash

# Installs Domino container script

CURRENT_DIR=$(pwd)
SCRIPT_DIR=$(dirname $0)
START_SCRIPT_TAR=$SCRIPT_DIR/../dockerfiles/install_dir_domino/domino-startscript.taz

tar -C /tmp -xf $START_SCRIPT_TAR

cd /tmp/domino-startscript
./install_domino_container
cd ..

cd $CURRENT_DIR
rm -rf /tmp/domino-startscript
